### ISSUE TITLE
空指针错误

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/didano-platform-base#103]
java.lang.NumberFormatException: For input string: "null"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at cn.didano.video.auth.ws.VideoWebSocketHandler.afterConnectionEstablished(VideoWebSocketHandler.java:196)

**Comment by yang55** [comment]
第一：Video websocket配置，在对应的类中的196行代码如下所示：
int studentId = Integer.parseInt(vars.get("studentId"));、
第二：我没有修改过这里面的代码，神策数据以及统计都是由刘华进行的。
第三："null"指针异常，应该是没有得到学生id导致的，并且没有做异常处理，直接往外面抛出的异常。

**Comment by stephenwang2017** [comment]
studentId = Integer.parseInt(vars.get("studentId"));
channelId = Integer.parseInt(vars.get("channelId"));

--->

int studentId = 0;
		int channelId = 0; 
		try{
			studentId = Integer.parseInt(vars.get("studentId"));
			channelId = Integer.parseInt(vars.get("channelId"));
		}catch(NumberFormatException ex){
			logger.warn(ex.getMessage());
		}
